# Generated by Django 5.1.6 on 2025-03-21 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_variations"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Variations",
            new_name="Variation",
        ),
    ]
