# Generated by Django 5.1.6 on 2025-04-20 03:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_productrating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductRating",
            new_name="ReviewRating",
        ),
    ]
