# Generated by Django 5.1.6 on 2025-03-22 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_cartitem_variations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="variations",
        ),
    ]
