# Generated by Django 5.1.6 on 2025-04-07 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="address_line1",
            new_name="address1",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="address_line2",
            new_name="address2",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="phone",
            new_name="phone_number",
        ),
    ]
